export const stateandcity = {
    "Select State": ["select city"],
    "Andhra Pradesh": [
      "select city", 
      "Visakhapatnam", 
      "Vijayawada", 
      "Guntur", 
      "Nellore", 
      "Kurnool", 
      "Tirupati", 
      "Rajahmundry", 
      "Kakinada", 
      "Anantapur", 
      "Kadapa"
    ],
    "Maharashtra": [
      "select city", 
      "Mumbai", 
      "Pune", 
      "Nagpur", 
      "Nashik", 
      "Aurangabad", 
      "Thane", 
      "Solapur", 
      "Kolhapur", 
      "Amravati", 
      "Sangli"
    ],
    "Tamil Nadu": [
      "select city", 
      "Chennai", 
      "Coimbatore", 
      "Madurai", 
      "Tiruchirappalli", 
      "Salem", 
      "Tirunelveli", 
      "Erode", 
      "Vellore", 
      "Thoothukudi", 
      "Dindigul"
    ],
    "Uttar Pradesh": [
      "select city", 
      "Lucknow", 
      "Kanpur", 
      "Agra", 
      "Varanasi", 
      "Meerut", 
      "Allahabad", 
      "Bareilly", 
      "Aligarh", 
      "Moradabad", 
      "Ghaziabad"
    ],
    "Assam": [
      "select city", 
      "Guwahati", 
      "Silchar", 
      "Dibrugarh", 
      "Jorhat", 
      "Nagaon", 
      "Tezpur", 
      "Tinsukia", 
      "Karimganj", 
      "Golaghat", 
      "Sibsagar"
    ],
    "Arunachal Pradesh": [
      "select city", 
      "Itanagar", 
      "Naharlagun", 
      "Tawang", 
      "Pasighat", 
      "Roing", 
      "Ziro", 
      "Bomdila", 
      "Tezu", 
      "Aalo", 
      "Khonsa"
    ],
    "Manipur": [
      "select city", 
      "Imphal", 
      "Thoubal", 
      "Bishnupur", 
      "Churachandpur", 
      "Senapati", 
      "Ukhrul", 
      "Tamenglong", 
      "Jiribam", 
      "Kangpokpi", 
      "Moirang"
    ],
    "Nagaland": [
      "select city", 
      "Kohima", 
      "Dimapur", 
      "Mokokchung", 
      "Tuensang", 
      "Wokha", 
      "Mon", 
      "Phek", 
      "Zunheboto", 
      "Kiphire", 
      "Longleng"
    ],
    "Rajasthan": [
      "select city", 
      "Jaipur", 
      "Jodhpur", 
      "Udaipur", 
      "Kota", 
      "Ajmer", 
      "Bikaner", 
      "Alwar", 
      "Bharatpur", 
      "Pali", 
      "Sikar"
    ],
    "Karnataka": [
      "select city", 
      "Bengaluru", 
      "Mysuru", 
      "Hubballi", 
      "Mangaluru", 
      "Belagavi", 
      "Davangere", 
      "Kalaburagi", 
      "Shivamogga", 
      "Ballari", 
      "Tumakuru"
    ],
    "West Bengal": [
      "select city", 
      "Kolkata", 
      "Howrah", 
      "Durgapur", 
      "Asansol", 
      "Siliguri", 
      "Kharagpur", 
      "Bardhaman", 
      "Malda", 
      "Haldia", 
      "Jalpaiguri"
    ],
    "Kerala": [
      "select city", 
      "Thiruvananthapuram", 
      "Kochi", 
      "Kozhikode", 
      "Thrissur", 
      "Kollam", 
      "Kannur", 
      "Alappuzha", 
      "Palakkad", 
      "Kottayam", 
      "Malappuram"
    ],
    "Gujarat": [
      "select city", 
      "Ahmedabad", 
      "Surat", 
      "Vadodara", 
      "Rajkot", 
      "Bhavnagar", 
      "Jamnagar", 
      "Junagadh", 
      "Gandhinagar", 
      "Anand", 
      "Navsari"
    ],
    "Punjab": [
      "select city", 
      "Ludhiana", 
      "Amritsar", 
      "Jalandhar", 
      "Patiala", 
      "Bathinda", 
      "Mohali", 
      "Hoshiarpur", 
      "Moga", 
      "Pathankot", 
      "Firozpur"
    ],
    "Madhya Pradesh": [
      "select city", 
      "Indore", 
      "Bhopal", 
      "Gwalior", 
      "Jabalpur", 
      "Ujjain", 
      "Sagar", 
      "Ratlam", 
      "Rewa", 
      "Satna", 
      "Dewas"
    ],
    "Bihar": [
      "select city", 
      "Patna", 
      "Gaya", 
      "Bhagalpur", 
      "Muzaffarpur", 
      "Darbhanga", 
      "Arrah", 
      "Begusarai", 
      "Katihar", 
      "Purnia", 
      "Saharsa"
    ]
  };
  
